### ISSUE TITLE
Does eloipool supports a ExtranonceSubscribe option?

### ISSUE THREAD

**Issue by jeong760** [luke-jr/eloipool#10]
Dears,

Does eloipool supports a ExtranonceSubscribe option? because I am uses a stratum-proxy as eloipool monitoring purchase there is an option for enableExtranonceSubscribe. 
However when I set it as true then I've get following error messages. so I wonder if there is any option for this function on eloipool.

2016-04-27 00:29:29,867 ERROR [Pool-Eloipoolsrv-Thread]: [PoolConnection]    Pool-Eloipoolsrv. JSON-RPC parsing error with line: {"id": 4, "result": null, "error": [-3, "Method 'mining.extranonce.subscribe' not found", null]}. java.lang.NullPointerException
    at strat.mining.stratum.proxy.pool.Pool.processSubscribeExtranonceResponse(Pool.java:492)
    at strat.mining.stratum.proxy.pool.PoolConnection.onExtranonceSubscribeResponse(PoolConnection.java:142)
    at strat.mining.stratum.proxy.network.StratumConnection.onResponseReceived(StratumConnection.java:322)
    at strat.mining.stratum.proxy.network.StratumConnection.onLineRead(StratumConnection.java:240)
    at strat.mining.stratum.proxy.network.StratumConnection.access$200(StratumConnection.java:59)
    at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:163)

2016-04-27 00:30:07,239 INFO  [StratumProxyManagerSeverSocketListener]: [ProxyManager]    New connection on /192.168.1.2:3333 from /54.94.211.146:52723.
2016-04-27 00:30:07,239 ERROR [54.94.211.146-Thread]: [WorkerConnection]    Parsing error on worker connection 54.94.211.146. Failed to parse line 夏다version     j   ?퀈`?          v?W                     ??y?9?.
com.fasterxml.jackson.core.JsonParseException: Unrecognized token '夏다version     j   ': was expecting ('true', 'false' or 'null')
 at [Source: 夏다version     j   ?퀈`?          v?W                     ??y?9?; line: 1, column: 19]
    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2300)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1459)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3600)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2576)
    at strat.mining.stratum.proxy.network.StratumConnection.onLineRead(StratumConnection.java:225)
    at strat.mining.stratum.proxy.network.StratumConnection.access$200(StratumConnection.java:59)
    at strat.mining.stratum.proxy.network.StratumConnection$1.run(StratumConnection.java:163)

Regards,
John Ahn

**Comment by luke-jr** [comment]
No, it isn't useful.

**Comment by jeong760** [comment]
Dears,

Do you have any plan improvement of Eloipool? 
- Var diff support
- Web API support
- SQL DB support

Regards,
John Ahn  
-----Original Message-----

**Comment by luke-jr** [comment]
Dynamic targetting ("var diff") and SQL db are both already supported. I don't see a point of a web API.

**Comment by jeong760** [comment]
Dears,

Could you guide me a setting of Dymanic targetting? becuase I was try to setup it but it always set on Diff 1 or Diff 56
and web api means like following picture. 

and also I want to know how I create a SQL DB table for Eloipool for logging and Sharelog.

&lt;Picture&gt; Web monitoring example.

Regards,
John Ahn 
-----Original Message-----

**Comment by luke-jr** [comment]
Take config.py.example and just set DynamicTargetting to 1 or 2.

Eloipool isn't picky about SQL schema, you can have it do any SQL call you need.

Your picture did not come through.

**Comment by jeong760** [comment]
Dears,

I saw following errors in log file but I don't know how I fixed it. 

2016-04-28 18:54:30,150 merkleMaker     CRITICAL        Traceback (most recent call last):
  File "/eloipoolsrv/merklemaker.py", line 704, in run
    self.merkleMaker_I()
  File "/eloipoolsrv/merklemaker.py", line 694, in merkleMaker_I
    self.merkleMaker_II()
  File "/eloipoolsrv/merklemaker.py", line 672, in merkleMaker_II
    return self._updateMerkleTree()
  File "/eloipoolsrv/merklemaker.py", line 560, in _updateMerkleTree
    self._updateMerkleTree_I()
  File "/eloipoolsrv/merklemaker.py", line 546, in _updateMerkleTree_I
    raise RuntimeError('Failed to create usable template')
RuntimeError: Failed to create usable template 

Regards,
John Ahn 

-----Original Message-----
