### ISSUE TITLE
The logfiel size is too big due to error message of merkleMaker_I and II

### ISSUE THREAD

**Issue by jeong760** [luke-jr/eloipool#11]
Dears,

I saw following error on logfile of eloipool. so I was looking for method to fix following error but there is not clear solution for this. even I've read a post on bitcointalk.org. 
So please let me know how I fixed this issue? because of error message logfiles are too big...it almost 40GB per day log. 

2016-04-30 04:21:11,338 BitcoinRPC      DEBUG   -1-> getblocktemplate [{"capabilities": ["coinbasevalue", "coinbase/append$
2016-04-30 04:21:11,365 BitcoinRPC      DEBUG   <-1- {"coinbasevalue": 2527191892, "capabilities": ["proposal"], "sizelimi$
2016-04-30 04:21:11,371 merkleMaker     INFO    New block: 000000000000000001893e44352e7cd4c7e33d8249068bee3d9ab5f47ae375b$
2016-04-30 04:21:11,372 JSONRPCServer   INFO    Waiting 15 seconds to longpoll
2016-04-30 04:21:11,381 BitcoinRPC      DEBUG   -2-> getblocktemplate [{"mode": "proposal", "data": "04000000b575e37af4b59$
2016-04-30 04:21:11,394 BitcoinRPC      DEBUG   <-2- null
2016-04-30 04:21:11,395 BitcoinRPC      DEBUG   -3-> getblocktemplate [{"capabilities": ["coinbasevalue", "coinbase/append$
2016-04-30 04:21:11,447 BitcoinRPC      DEBUG   <-3- {"coinbasevalue": 2527191892, "capabilities": ["proposal"], "sizelimi$
2016-04-30 04:21:11,463 BitcoinRPC      DEBUG   -4-> getblocktemplate [{"mode": "proposal", "data": "04000000b575e37af4b59$
2016-04-30 04:21:11,476 BitcoinRPC      DEBUG   <-4- null
2016-04-30 04:21:11,476 merkleMaker     CRITICAL        Traceback (most recent call last):  File "/eloipoolsrv/merklemaker.py", line 704, in run   self.merkleMaker_I()
File "/eloipoolsrv/merklemaker.py", line 694, in merkleMaker_I  self.merkleMaker_II()
File "/eloipoolsrv/merklemaker.py", line 660, in merkleMaker_II   return self._updateMerkleTree()
File "/eloipoolsrv/merklemaker.py", line 560, in _updateMerkleTree  self._updateMerkleTree_I()
File "/eloipoolsrv/merklemaker.py", line 546, in _updateMerkleTree_I  raise RuntimeError('Failed to create usable template') RuntimeError: Failed to create usable template

Regards,
John Ahn

**Comment by luke-jr** [comment]
Don't set debug log level...

**Comment by jeong760** [comment]
Where can I set a debug? I was used it just copy and past from config sample.
-----Original Message-----
