### ISSUE TITLE
I've got error lelated with merkelMaker.

### ISSUE THREAD

**Issue by jeong760** [luke-jr/eloipool#17]
Dear Luke-jr

I've got following error on my Eloipool. but I don't know exactly what should I do. 
Could you give me tip or guide for setting or check point for this error?

2017-03-20 21:37:17,375 merkleMaker     ERROR   Traceback (most recent call last):
  File "/home/linuxadm/eloipool/merklemaker.py", line 606, in _updateMerkleTree_I
    r = self._updateMerkleTree_fromTS(TS)
  File "/home/linuxadm/eloipool/merklemaker.py", line 578, in _updateMerkleTree_fromTS
    (AcceptedScore, TotalScore) = self._CheckTemplate(newMerkleTree, TS)
  File "/home/linuxadm/eloipool/merklemaker.py", line 525, in _CheckTemplate
    propose = caccess.getblocktemplate(ProposeReq)
  File "/home/linuxadm/eloipool/bitcoinrpc/authproxy.py", line 136, in __call__
    'Content-type': 'application/json'})
  File "/usr/lib/python3.4/http/client.py", line 1125, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1153, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.4/http/client.py", line 993, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent

2017-03-20 21:37:17,379 merkleMaker     CRITICAL        Traceback (most recent call last):
  File "/home/linuxadm/eloipool/merklemaker.py", line 793, in run
    self.merkleMaker_I()
  File "/home/linuxadm/eloipool/merklemaker.py", line 783, in merkleMaker_I
    self.merkleMaker_II()
  File "/home/linuxadm/eloipool/merklemaker.py", line 761, in merkleMaker_II
    return self._updateMerkleTree()
  File "/home/linuxadm/eloipool/merklemaker.py", line 649, in _updateMerkleTree
    self._updateMerkleTree_I()
  File "/home/linuxadm/eloipool/merklemaker.py", line 606, in _updateMerkleTree_I
    r = self._updateMerkleTree_fromTS(TS)
  File "/home/linuxadm/eloipool/merklemaker.py", line 569, in _updateMerkleTree_fromTS
    MP = self._CallGBT(TS)
  File "/home/linuxadm/eloipool/merklemaker.py", line 381, in _CallGBT
    MP = access.getblocktemplate(self.GBTReq)
  File "/home/linuxadm/eloipool/bitcoinrpc/authproxy.py", line 136, in __call__
    'Content-type': 'application/json'})
  File "/usr/lib/python3.4/http/client.py", line 1125, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1153, in _send_request
    self.putrequest(method, url, **skips)

Regards,
John Ahn

**Comment by dmp1ce** [comment]
I was able to get past this issue by allowing access to the `.bitcoin` directory. I then had another issue though which is the following:

```
2020-04-27 23:59:18,221 merkleMaker     CRITICAL        Traceback (most recent call last):
  File "/home/user/eloipool/merklemaker.py", line 793, in run
    self.merkleMaker_I()
  File "/home/user/eloipool/merklemaker.py", line 783, in merkleMaker_I
    self.merkleMaker_II()
  File "/home/user/eloipool/merklemaker.py", line 749, in merkleMaker_II
    return self._updateMerkleTree()
  File "/home/user/eloipool/merklemaker.py", line 649, in _updateMerkleTree
    self._updateMerkleTree_I()
  File "/home/user/eloipool/merklemaker.py", line 606, in _updateMerkleTree_I
    r = self._updateMerkleTree_fromTS(TS)
  File "/home/user/eloipool/merklemaker.py", line 570, in _updateMerkleTree_fromTS
    newMerkleTree = self._ProcessGBT(MP, TS)
  File "/home/user/eloipool/merklemaker.py", line 468, in _ProcessGBT
    cbtxn = self.makeCoinbaseTxn(MP['coinbasevalue'], prevBlockHex = MP['previousblockhash'], witness_commitment=witness_commitment)
  File "eloipool.py", line 134, in makeCoinbaseTxn
    pkScript = BitcoinScript.toAddress(config.TrackerAddr)
  File "/home/user/eloipool/bitcoin/script.py", line 41, in toAddress
    raise ValueError('invalid address')
ValueError: invalid address
```

I checked my `TrackerAddr` and it appears to be correct.
