### ISSUE TITLE
How to install / use it?

### ISSUE THREAD

**Issue by ghost** [luke-jr/eloipool#2]
I get this error when I try to install it, I really don't know what I'm doing & could use some instructions on how to get started. Thanks.

$ python eloipool.py install
usage: eloipool.py [-h] [-c CONFIG]
eloipool.py: error: unrecognized arguments: install

**Comment by luke-jr** [comment]
Eloipool is not meant to be installed. Just run it from the git clone directory.

Help documenting usage would be welcome.

**Comment by ghost** [comment]
I started on install instructions, based on my experience thus far. They're here (incomplete):
http://pastebin.com/BGPbFZS8

**Comment by ghost** [comment]
I'm still having trouble running it, apparently I'm doing something wrong- I do 'python eloipool.py' as user, & I get these errors:

~/apps/eloipool$ python eloipool.py                                Traceback (most recent call last):
  File "eloipool.py", line 82, in <module>
    bcnode = BitcoinNode(config.UpstreamNetworkId)
  File "/home/admin/apps/eloipool/bitcoin/node.py", line 146, in **init**
    super().**init**(_a, *_ka)
TypeError: super() takes at least 1 argument (0 given)
admin@crypt0:~/apps/eloipool$

Might this be due to there being no bitcoind running?

**Comment by luke-jr** [comment]
Looks more like an obsolete version of Python.

**Comment by ghost** [comment]
There are a few versions installed to my OS:
python3.4-minimal
python3.4-dev
python3-minimal
python3-dev
python3-all
python3-all-dev
python3
python2.7
python2.7-minimal

These are the newest in Ubuntu 14.04 apparently since I don't see any higher version numbers when I do:
sudo aptitude search python|grep 3

Also, when I try to purge python2.7 & python2.7-minimal
I get aptitude wanting to uninstall stuff I need.

I imagine eloipool is using 2.7 instead of 3.x based on what your saying now. Don't quite know how to fix that other than uninstalling 2.7- so now I'm a bit lost.

**Comment by luke-jr** [comment]
python3 eloipool.py 

?

**Comment by ghost** [comment]
Oh, ok- I had no idea it would be so easy... :-D Thanks!

**Comment by ghost** [comment]
Now I get:
import jsonrpc
ImportError: No module named 'jsonrpc'

Maybe because bitcoind hasn't finished syncing?

**Comment by ghost** [comment]
The only way I was able to get it to start at boot 'as user' was to start it in a screen session (which detaches itself) & doing 'su username -c' before this startup command:

PYTHONPATH=/bitcoin/python-bitcoinrpc:/bitcoin/python-base58:/bitcoin/midstate \
     nohup ./eloipool.py 2>&1 >/dev/null &

Now it shows up in htop, screenshot: https://imgur.com/fhJ4FMG

So now how can I test that it works?
